# fly.toml app configuration file generated for club-prod on 2026-01-23T02:36:14+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "club-prod"
primary_region = "fra"
console_command = "/rails/bin/rails console"

[build]

[deploy]
  release_command = "./bin/rails db:prepare"

[processes]
  web = "bin/rails server"
  jobs = "bundle exec rake solid_queue:start"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = true
  min_machines_running = 1
  processes = ["web"]

  [[http_service.checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    method = "GET"
    path = "/up"
    protocol = "http"
    tls_skip_verify = false

    [http_service.checks.headers]
      X-Forwarded-Proto = "https"

[[vm]]
  memory = "512mb"
  cpus = 1
  memory_mb = 512

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
